service: my-serverless-app

provider:
 name: aws
 runtime: nodejs14.x
 memorySize: 128
 timeout: 10
 stage: production
 region: ap-south-1

functions:
 api:
   handler: lambda.universal
   events:
     - http: ANY {proxy+}
     - http: ANY /


# Add deploy script to package.json:
# "scripts": {
#  "start": "nodemon ./bin/www.js,
#  "deploy": "serverless deploy"
# }
